### PR TITLE
Swift 3.1 Conversion

### PR DESCRIPTION
**Pull request by stulevine**
- Converted to swift 3.1 in Xcode 8.3
- Added MazeMaker workspace in order to embed and utilize the MazeMaker framework in a playground
- Added working playground example

### CODE REVIEW

**Comment by stulevine** [comment]
@jamis not sure if you received any notifications on this repo.  However, I did create a PR for some changes related to Swift 3.x conversion and added a working playground.  Please let me know if you have any questions.

**Comment by jamis** [comment]
This looks really great! Thanks for undertaking this. I'll look it over more carefully this evening, but I don't anticipate any problems.

**Comment by jamis** [comment]
Thanks again! I've not had a chance to do much with Swift for a while, but looking at your changes makes me eager to play with Swift 3.

**Comment by stulevine** [comment]
Jamis,

Awesome!  Also wanted to let you know that I did purchase your book “Mazes for Programmers" and this was the driving force behind my PR.  I’m a Sr. iOS Software Engineer, and while I do know a little Ruby, it’s def not my first language. When I found this repo I was really excited to see some of the book’s concepts applied in Swift.  I utilize Swift and Obj-C daily so it’s my primary focus atm.  Thanks for taking the time to put this together.  It was rather rudimentary to convert to Swift 3.1 and include a working playground since I’ve gone through two conversions already for my own apps and the company I work for.

Cheers,

Stuart

**Pull request merged**
